name: Dump

on:
    schedule:
        - cron: "0 */6 * * *"
    workflow_dispatch:

jobs:
    dump:
        name: Dump
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Move Old Files
              run: |
                  mkdir leetcode
                  mv * .gitignore .gitattributes .*.json leetcode
              continue-on-error: true

            - name: Install leetcode-dump
              run: npm i -g leetcode-dump && lcd -V

            - name: Dump Solutions
              run: lcd -l 2/1 -T ./leetcode/index-template.md
              env:
                  LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}

            - name: Build Static Site
              run: lcd build
              env:
                  CNAME: leetcode.jacoblin.cool

            - name: Copy Workflows
              run: cp -R .github/ ./leetcode/.github/

            - name: Deploy Dumped Solutions
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN  }}
                  publish_dir: "./leetcode"
                  publish_branch: "main"
                  full_commit_message: "Update Solutions [ci skip]"
                  exclude_assets: ""

            - name: Deploy Static Site
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN  }}
                  publish_dir: "./site"
                  publish_branch: "gh-pages"
                  full_commit_message: "Update Solutions [ci skip]"
